### ISSUE TITLE
cannot import LLMFullResponseEndFrame

### ISSUE THREAD

**Issue by janwout** [pipecat-ai/pipecat#154]
when trying v0.0.18, this error is given on loading the story page

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jwee/projects/pipecat/examples/storytelling-chatbot/src/bot.py", line 18, in <module>
    from processors import StoryProcessor, StoryImageProcessor
  File "/home/jwee/projects/pipecat/examples/storytelling-chatbot/src/processors.py", line 5, in <module>
    from pipecat.frames.frames import (
ImportError: cannot import name 'LLMFullResponseEndFrame' from 'pipecat.frames.frames' (/home/jwee/envs/alfabert/lib/python3.10/site-packages/pipecat/frames/frames.py)
```

**Comment by aconchillo** [comment]
Hi @janwout . This is probably because you have updated the repo (and therefore the examples) but you haven't installed latest `pipecat-ai`. So, from the `storytelling-chatbot` directory do `pip install -U pipecat-ai`.

Also, we just released 0.0.18 which fixes the microphone on `storytelling-chatbot`. I believe you were having issues before. That version should fix it.

**Comment by aconchillo** [comment]
I have also updated `storytelling-chatbot` README.md to make sure it's up to date. Another user on Discord just acknowledged that works for them.

Please, let us know!

**Comment by janwout** [comment]
ah yes, that did it, thank you!
