### ISSUE TITLE
[Question] React Native Integration with Pipecat and Daily

### ISSUE THREAD

**Issue by gaceladri** [pipecat-ai/pipecat#277]
Hi Pipecat Team,

I'm exploring the integration of Pipecat (Pipeline: Speech-to-text -> LLM -> Text-to-Speech) into my React Native app using Expo. I have a couple of questions on the best approach for this integration:

1. **Daily Integration:** Should Daily be integrated directly within my app's client, or would it be more efficient to deploy Pipecat to AWS (perhaps using a Lambda architecture with state management) and have the Expo app communicate with the cloud service and all the pipecat code living in aws?

1. **Best Practices:** Are there any specific best practices or recommendations you have for integrating Pipecat with a React Native app, especially considering the constraints and capabilities of Expo?

Any guidance or examples you could provide would be greatly appreciated!

Thank you for your help!

**Comment by gaceladri** [comment]
Related to https://github.com/pipecat-ai/pipecat/issues/152

**Comment by aconchillo** [comment]
Hi @gaceladri ! I know this is closed but here are some answers:

1. Pipecat is a server side thing so you can host it wherever you want. The Pipecat bot/agent will just connect to the Daily room. To integrate with Daily in the client you can just use `daily-react` or `daily-js` directly. That will be your client application which you can also host anywhere. Since you are using Daily you can send message from the Pipecat bot to the client UI using `DailyTransportMessageFrame`. The `storytelling-chatbot` examples shows how to do that.
2. If you use Daily and want to use React, `daily-react` is probably the best option. 

daily-react: https://github.com/daily-co/daily-react
daily-js: https://github.com/daily-co/daily-js

**Comment by gaceladri** [comment]
@aconchillo Thank you for your answer! I closed this since @jptaylor shared some examples of clients I could adapt
