### ISSUE TITLE
Interruptions not working with websocket-server

### ISSUE THREAD

**Issue by Cuanmaomao** [pipecat-ai/pipecat#456]
I ran the sample code of examples/websocket-server but noticed that the user cannot interrupt.

**Comment by dk-crazydiv** [comment]
Same. When using with DailyTransport, logs have "User started speaking" an "User stopped speaking" messages but when shifting to websocket it doesn't work. As a result overlapping voices are getting played ( previous user query response and current user query response )

**Comment by dk-crazydiv** [comment]
Yes the VAD interrupt works normally in all the pipecat supported transports as far as I could tell. The only problem with websocket is that interrupt got caught on backend services but if some audio frames are already delivered to a frontend html/js client, by default websocket implementation didn't contain any mechanism to forward that interrupt signal to the frontend. 

The makefix solution I used to workaround this issue was to inherit `WebsocketServerOutputTransport` and write my own hook to send the data in `process_frame`.

```
async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)
        if isinstance(frame, StartInterruptionFrame):
                # INTERRUPT WEBSOCKET HANDLING
                text_frame = TextFrame(f"TYPE:INTERRUPT---MESSAGE:USER_STARTED_SPEAKING")
                proto = self._params.serializer.serialize(text_frame)
                await self._websocket.send(proto)
```

Then parse this TextFrame on frontend to clear the audiobuffer.

**Comment by geereddysath** [comment]
@dk-crazydiv can you also help with how you clear the audiobuffer?

**Comment by aconchillo** [comment]
This is now fixed by this PR https://github.com/pipecat-ai/pipecat/pull/687 and should be availabe in next Pipecat release.
