### ISSUE TITLE
question: is it possible to send arbitrary specific app messages from pipecat to client using RTVI 2.0?

### ISSUE THREAD

**Issue by brelig** [pipecat-ai/pipecat#614]
Is there a defined approach to do this in RTVI & Pipecat? I see on the onGenericMessage callback in the rtvi client but I don't see any pipecat frame messages that allow for this. Any suggestions?

**Comment by aconchillo** [comment]
Hi @brelig ! You can try sending a `TransportMessageUrgentFrame` and copy one of the existing RTVI messages, for example: 

https://github.com/pipecat-ai/pipecat/blob/main/src/pipecat/processors/frameworks/rtvi.py#L337-L340

All you need is the `rtvi-ai` label and a custom `type` value. 

Then you can just send it downstream:

```
        frame = TransportMessageUrgentFrame(message=message.model_dump(exclude_none=exclude_none))
        await self.push_frame(frame)
```

If the message is not handled by RTVI client (which it will not since you set your custom type) you will then get it through the `onGenericMessage` callback.

**Comment by markbackman** [comment]
@brelig I agree with @aconchillo. This is the recommended approach. If you have any other questions, feel free to drop ask in Discord or reopen the issue.

**Comment by anastasiosyal** [comment]
The updated idiomatic way of sending custom messages from the server is to send an [RTVIServerMessageFrame](https://reference-server.pipecat.ai/en/latest/api/pipecat.processors.frameworks.rtvi.html#pipecat.processors.frameworks.rtvi.RTVIServerMessageFrame)   

This will trigger an `onServerMessage` on the client side, where you can attach your event handler to manage your custom payload.
